### ISSUE TITLE
Fluent Builder for Additional Ports 

### ISSUE THREAD

**Issue by saig0** [camunda-community-hub/zeebe-test-container#103]
**Is your feature request related to a problem? Please describe.**
I have a JUnit 5 test and want to expose additional ports (i.e. for the Hazelcast exporter). If I use the fluent builder to add a port then it overwrites the default broker ports.

```
@Container
var zeebe = ZeebeContainer()
    .withEnv("ZEEBE_BROKER_EXPORTERS_HAZELCAST_CLASSNAME", "io.zeebe.hazelcast.exporter.HazelcastExporter")
    .withEnv("ZEEBE_BROKER_EXPORTERS_HAZELCAST_JARPATH", "exporter/zeebe-hazelcast-exporter.jar")
    .withCopyFileToContainer(MountableFile.forHostPath(exporterJarPath), containerPath)
    .withExposedPorts(hazelcastPort)
```

**Describe the solution you'd like**
I want to add the additional ports using the fluent builder. 

**Describe alternatives you've considered**
Don't use the fluent builder and add the ports later.

```
@Container
var zeebe = zeebeContainer()

private fun zeebeContainer(): ZeebeContainer {
    val container = ZeebeContainer()
        .withEnv("ZEEBE_BROKER_EXPORTERS_HAZELCAST_CLASSNAME", "io.zeebe.hazelcast.exporter.HazelcastExporter")
        .withEnv("ZEEBE_BROKER_EXPORTERS_HAZELCAST_JARPATH", "exporter/zeebe-hazelcast-exporter.jar")
        .withCopyFileToContainer(MountableFile.forHostPath(exporterJarPath), containerPath)
   
   container.addExposedPort(hazelcastPort)
   return container
}
```

**Additional context**
I use the test-container in a JUnit 5 test with the Hazelcast exporter.

**Comment by npepinpe** [comment]
Hopefully fixed in master, will try to release soon. There is now a new API which you can use:

```java
final ZeebeContainer c = new ZeebeContainer().withAdditionalExposedPort(8080).withEnv("...", "...");
```

This will not overwrite existing ports. See `ZeebeNode#withAdditionalExposedPort(int)` for more.
