### ISSUE TITLE
Ability to enable monitoring for the standalone gateway via the convenient method in ZeebeClusterBuilder 

### ISSUE THREAD

**Issue by aivinog1** [camunda-community-hub/zeebe-test-container#140]
**Is your feature request related to a problem? Please describe.**
As a user, I should be able to enable the monitoring endpoint for the cluster easily by calling one method in `io.zeebe.containers.cluster.ZeebeClusterBuilder`.

**Describe the solution you'd like**
I would prefer to have a single method like `public ZeebeClusterBuilder withStandaloneMonitoring()` or something like that.

**Describe alternatives you've considered**
The ability to set environment variables for a standalone gateway would works for this case too.

**Comment by npepinpe** [comment]
Superseded by https://github.com/camunda-community-hub/zeebe-test-container/issues/150
