### ISSUE TITLE
Allow arbitrary configuration of brokers/gateways via the cluster builder

### ISSUE THREAD

**Issue by npepinpe** [camunda-community-hub/zeebe-test-container#150]
**Is your feature request related to a problem? Please describe.**

It's currently possible to configure the broker/gateway that form a cluster after building them by accessing them as:

```java
cluster.getBrokers().values().forEach(b -> b.withEnv("FOO", "BAR");
```

However, it doesn't really make use of the builder pattern, and it prevents using the cluster as a `@Rule` or extension in the future - well not prevent, but it means you can't use it and configure the brokers arbitrarily afterwards.

See also these issues which try to address specific properties:

- https://github.com/camunda-community-hub/zeebe-test-container/issues/140
- https://github.com/camunda-community-hub/zeebe-test-container/issues/139

**Describe the solution you'd like**

Instead of trying to figure out all the properties a user might want to be build, I would rather keep the API surface small, and just let users pass a `UnaryOperator` which takes in a broker/gateway and returns a configured one, e.g.

```java
cluster.withBrokerConfig(b -> b.withEnv("foo")).build();
```

Some open questions:

- Should we have three methods, `withBrokerConfig`, `withGatewayConfig`, and `withNodeConfig`, which target the various specific node types (where the `withNodeConfig` is applied to both brokers and gateways)?
- Should the configuration methods be applied after or before the cluster's own configuration? Intuitively I think after, but I'm open to discussion.

**Describe alternatives you've considered**

Adding specific builder methods for each property that we want to configure. This has the advantage that we have better control over the 

**Additional context**

- https://github.com/camunda-community-hub/zeebe-test-container/issues/140
- https://github.com/camunda-community-hub/zeebe-test-container/issues/139
- https://github.com/camunda-community-hub/zeebe-test-container/pull/143
- https://github.com/camunda-community-hub/zeebe-test-container/pull/145

/cc @aivinog1 since you've worked on these issues

**Comment by aivinog1** [comment]
Hey @npepinpe! So, as I understand should we close #140 and #139 and focus on this solution? Am I properly understand these words:
> Should the configuration methods be applied after or before the cluster's own configuration? Intuitively I think after, but I'm open to discussion.

So, do you propose something like this (let's focusing on order)?
```
var clusterBuilder = ZeebeCluster.builder();
clusterBuilder.withEmbeddedGateway(false).withBrokersCount(1).withGatewaysCount(1);
var cluster = clusterBuilder.build().withBrokerConfig(b -> b.withEnv("foo"));
```
Or should we maintain order in the builder? If we chose the second option, can you elaborate a little (with a full example with builder and cluster objects)?

**Comment by npepinpe** [comment]
I would propose on the builder itself. So instead of adding a method in the builder for all the things we want to configure for the gateway/broker, we can just do that in a more generic way:

```java
final var cluster = ZeebeCluster.builder()
  .withEmbeddedGateway(false)
  .withBrokersCount(1)
  .withGatewaysCount(1)
  .withNodeConfig(node -> node.setDockerImage(ZeebeDefaults.getInstance().getDockerImage().withTag("1.0.1")))
  .withBrokerConfig(broker -> broker.withEnv("foo", "broker"))
  .withGatewayConfig(gateway -> gateway.withEnv("foo", "gateway"))
  .build();
```

**Comment by aivinog1** [comment]
Hey @npepinpe! What do you think about if `UnaryOperator` would be replaced with `Consumer`? It is much easier to implement because you don't need to face typecasting.
