### ISSUE TITLE
Waiting for new release

### ISSUE THREAD

**Issue by sherry-ummen** [camunda-community-hub/zeebe-test-container#175]
Hi,

I just used latest release and bumped into a situation where it was unable to pull zeebe 1.0.0 , must be docker issue. but also then I realized we are not using latest zeebe as well. So this request is to please consider releasing a new version. Also 'How can I help?' to get it ready :)

Sherry

**Comment by npepinpe** [comment]
Will do next week :+1:

**Comment by sherry-ummen** [comment]
looks like you have been quite busy. any updates on this ? :)

**Comment by npepinpe** [comment]
3.1.0 is out. Unfortunately couldn't get #178 merged, but we can also do a 3.2.0 when it's merged.
