### ISSUE TITLE
Provide a user friendly API for test verifications

### ISSUE THREAD

**Issue by npepinpe** [camunda-community-hub/zeebe-test-container#6]
We should provide an easy to use API to assert certain things happen. At the moment, the container is a complete black box: it's fine to test workflows and workers, but is unusable for Zeebe itself.

By providing an API to better assert the current state of the container (for example, through a well known exporter), we could enable Zeebe to use this for end to end tests and backwards compability tests.

**Comment by npepinpe** [comment]
Some options considered:

1. Use the `DebugHttpExporter` exporter which is built-in Zeebe; it provides a JSON API from which we can grab all given records. The downside to this approach is that it's not straight-forward to rehydrate the JSON objects into Zeebe records in such a way that we could use the generated AssertJ classes (`zeebe-protocol-asserts`); so either we figure out a way to get our original records back, or we lose out on the quality of life features of the `zeebe-protocol-asserts` module.
1. Build a custom exporter which uses [kryo](https://github.com/EsotericSoftware/kryo) to serialize/deserialize records; this solves the problem above of getting our original records back, and so we can immediately use the `zeebe-protocol-asserts` module. The general idea would be that we have the exporter in the container which streams records out, and on ACK immediately updates the position; and on the test side, we have a receiver which buffers all records (optionally allow it to be evict based on size: use [caffeine](https://github.com/ben-manes/caffeine) for this maybe?). There's a few options for streaming: a shared Unix socket, TCP socket, gRPC, etc. gRPC is probably too heavy for this case, and Unix socket has the downside of blocking if the receiver is not consuming fast enough (is this an issue?).
1. The data volume could be shared between the containers and the tests, and we can read the log per-partition (assuming no deletion occurs). I'm listing this here mostly as a "yes I thought of it" but really it's a bad idea.

**Comment by npepinpe** [comment]
I'm currently working on this in a branch ([6-debug-exporter](https://github.com/zeebe-io/zeebe-test-container/tree/6-debug-exporter)). The current idea is:

1. Provide an exporter with no runtime dependencies but those provided by Zeebe and the JRE
1. Modify the build pipeline so the exporter is packaged as a resource of the main module
1. Add a configuration option to mount that exporter so it can be used from within the container

As for the exporter itself, in order to have no dependencies, it's built as:

1. Use [Immutables](https://immutables.github.io/) to generate serializable, immutable implementations of the Zeebe Protocol (so we don't have to write too much boilerplate); this is purely a compile-time dependency and is not necessary at runtime
1. The exporter will start a server thread, which accepts a single connection which can poll for X records.
1. Use a thread-safe, shared `ArrayBlockingQueue` between exporter and server thread; on `Exporter#export(Record)` call, we put the record in the queue. If the queue is full, we throw an exception so it is retried later.
1.  Once a client connect to the server thread, it will read up to X records, which are taken from the queue. We then write the number of records that will be transferred, followed by each record (using plain Java serialization).
1. On the client side, simply read everything back; immutables already generates how to deserialize the records back, which provides us with `Record<?>` on the client side. We can then use the protocol asserts as a nice API.

What is missing here is an analog of the `RecordingExporter` but for a client/server architecture. It shouldn't be extremely hard to figure something, however, but any help is welcome :)

**Comment by npepinpe** [comment]
There is also another solution currently in the works, which would provide a much nicer API overall for different use cases, but will probably be more work to achieve.

The idea would be to package the [Hazelcast Exporter](https://github.com/zeebe-io/zeebe-hazelcast-exporter/) as a resource of the main module, which can then be mounted at runtime if we need an exporter. We would keep the use of Immutables to re-hydrate our `Record<?>` POJOs from JSON, and provide a `RecordingExporter` like API for raw verifications. But by using the Hazelcast exporter, we could also use [zeeqs](https://github.com/zeebe-io/zeeqs/) to provide a nice GraphQL aggregated API for more general verifications - the two approaches combined should cover most use cases.

**Comment by B-hamza** [comment]
what about the RecordingExporter of Zeebe-test, do you think we can use the same to exports records using zeebe-test-container ?

**Comment by npepinpe** [comment]
It's a nice API, but at the moment the `RecordingExporter` wouldn't work here, at least how it's implemented - it's purely in memory. So if you start a container, which is basically a different process which may be living on a different node, you need to somehow cross that boundary back into your Java test. 

I've done it with Elastic - you can see an example here https://github.com/zeebe-io/zeebe-kafka-exporter/tree/master/tck (and how it's used here https://github.com/zeebe-io/zeebe-kafka-exporter/blob/master/qa/src/test/java/io/zeebe/exporters/kafka/qa/KafkaExporterIT.java

This is by the way a module I'm incubating there, it's very much a first draft :sweat_smile:

**Comment by npepinpe** [comment]
I believe this is planned to be officially covered by Camunda, so for now I will close this.
