### ISSUE TITLE
I can change the time of the broker

### ISSUE THREAD

**Issue by saig0** [camunda-community-hub/zeebe-test-container#74]
**Is your feature request related to a problem? Please describe.**
Sometimes, workflows have parts that are depending on the time or that time has passed. For example, a timer boundary event in a workflow. In order to test these parts, I need a way to manipulate the time.

**Describe the solution you'd like**
I can manipulate the time that is used by the broker from the outside.

**Describe alternatives you've considered**
Maybe, it is also possible to manipulate the time of the whole docker container.

**Additional context**

**Comment by npepinpe** [comment]
Do you think it's wise to allow this kind of manipulation for integration/acceptance tests? We want to test as close to production as possible, and manipulating time seems dangerous in that respect :sweat_smile: I get where you're coming from though, and I'm not saying we shouldn't - I'm rather on the fence, as I see the use and I think it might be a necessary evil.

Regardless, we can brainstorm a bit - how would it look like? Just a brain dump:

- I can imagine this feature would be impractical/not recommended for clustered set ups? I mean you'd have to somehow synchronize their clocks... :thinking: 
- I think manipulating system time/NTP has a good chance of breaking other things, so I would try to avoid going down that route :see_no_evil: But on the other hand, apart from that, I don't see any other way which doesn't involve code changes in Zeebe itself =/

**Comment by saig0** [comment]
Yes, I think it is a necessary function to test parts of the system. Otherwise, it is not possible for example to verify that the timer event in my workflow works as expected. 

I don't see the danger. Testcontainers are used for testing. So, this function will not be available in a production system. Yes, this is useful for a single broker only and will not work in a cluster.

I created an issue to expose an endpoint in the broker: https://github.com/zeebe-io/zeebe/issues/5289

**Comment by npepinpe** [comment]
Ah, I wasn't aware of the issue on the Zeebe side :+1:

**Comment by npepinpe** [comment]
Oops, wasn't aware this was enabled.

**Comment by npepinpe** [comment]
I did a quick spike of this last weekend, but I ran into issues when you change the complete actor clock (i.e. you trigger time outs, snapshots, etc.). It also made me realize that, in the future, if we also use the `ActorClock` for Raft, we would run into issues with time outs and leader changes possibly, so I'm unsure if this will be possible without some rethinking on the Zeebe side.

**Comment by saig0** [comment]
@npepinpe yes, good point. In Zeebe, the clock is coupled to more than just the workflow engine :sweat_smile:

**Comment by npepinpe** [comment]
So I lied, and I think I came up with a solution which sort of works. Now, this solution will mess clustered tests and shouldn't be used there, but if you're working only with a single node, it might be fine. You'll trigger unexpected time outs and so on, but I think it shouldn't affect your tests too much. At any rate, this is an experimental API, so we can try it out and see if the value it provides is worth the caveats.

**Comment by npepinpe** [comment]
I spent a bit more time thinking about this, and I while I definitely like libfaketime, the licensing thing is a bit of a pain. I thought it was a nice and non-intrusive solution (which I still think it is - and it was fun to work on :smile:), but as I said in the initial issue, I guess the best bet is to add an actuator to the Zeebe to modify the actor clock. So I'm going to close this again, sorry about that :smile:

**Comment by npepinpe** [comment]
FYI for those tracking this, the next Zeebe release (starting with 1.3.0-alpha2) will have an actuator that lets you change the clock of the broker by configuring `ZEEBE_CLOCK_CONTROLLED=true`, and then sending specific post requests to `/actuator/clock`. See this PR for more https://github.com/camunda-cloud/zeebe/pull/8180
